# Generated by Django 4.2.3 on 2024-12-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pallifund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=30)),
                ('reciept_no', models.CharField(max_length=30)),
                ('fund_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=6)),
                ('total_amount', models.CharField(max_length=6)),
                ('debit_credit', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
