# Generated by Django 4.2.3 on 2024-12-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_masapirivu'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmahallumembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=30)),
                ('family_members', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
    ]
