# Generated by Django 4.2.3 on 2024-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_addmahallumembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='addfamilymembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=30)),
                ('family_member', models.CharField(max_length=30)),
                ('relation', models.CharField(max_length=10)),
            ],
        ),
    ]
