# Generated by Django 4.2.3 on 2024-12-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_addfamilymembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmahallumembers',
            old_name='family_members',
            new_name='family_member',
        ),
    ]
