# Generated by Django 4.2.3 on 2024-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_family_members_addmahallumembers_family_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalfund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_no', models.CharField(max_length=30)),
                ('fund_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=6)),
            ],
        ),
    ]
