# Generated by Django 4.2.3 on 2024-12-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfamilymembers',
            name='relation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmahallumembers',
            name='relation',
            field=models.CharField(max_length=20),
        ),
    ]
